apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  annotations:
    definition.oam.dev/description: List the configs
  name: list-config
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        import (
        	"vela/op"
        )
        output: op.#ListConfig & {
        	if parameter.namespace != _|_ {
        		namespace: parameter.namespace
        	}
        	if parameter.namespace == _|_ {
        		namespace: context.namespace
        	}
        	template: parameter.template
        }
        parameter: {
        	//+usage=Specify the template of the config.
        	template: string
        	//+usage=Specify the namespace of the config.
        	namespace?: string
        }