apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  annotations:
    definition.oam.dev/description: Read a config
  name: read-config
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        import (
        	"vela/op"
        )
        output: op.#ReadConfig & {
        	name: parameter.name
        	if parameter.namespace != _|_ {
        		namespace: parameter.namespace
        	}
        	if parameter.namespace == _|_ {
        		namespace: context.namespace
        	}
        }
        parameter: {
        	//+usage=Specify the name of the config.
        	name: string
        	//+usage=Specify the namespace of the config.
        	namespace?: string
        }
